security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\User: 'auto'
    
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email # Ищем по email

    firewalls:
        # 1. dev должен быть первым!
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:
            pattern: ^/admin
            provider: app_user_provider
            form_login:
                login_path: admin_login
                check_path: admin_login
                default_target_path: admin
                enable_csrf: true
            logout:
                path: admin_logout
                target: admin_login
        
        # 2. Основной фаервол
        main:
            pattern: ^/(?!admin|api)
            lazy: true
            provider: app_user_provider # Добавляем связь с провайдером
            oauth:
                resource_owners:
                    yandex: "/connect/yandex/check"
                login_path: app_login
                failure_path: app_login
                default_target_path: app_home
                use_referer: true
                oauth_user_provider:
                    service: App\Security\OAuthUserProvider
            logout:
                path: app_logout
                target: app_home
        
        api:
            pattern: ^/api(?!\/admin)
            stateless: true
            provider: app_user_provider
            custom_authenticators:
                - App\Security\JwtAuthenticator
            entry_point: App\Security\JwtAuthenticator
    
    access_control:
        - { path: ^/admin/login$, roles: PUBLIC_ACCESS }
        - { path: ^/connect, roles: PUBLIC_ACCESS }
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/api/auth/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/auth/register, roles: PUBLIC_ACCESS }
        - { path: ^/api/auth/logout, roles: PUBLIC_ACCESS }
        - { path: ^/api, roles: ROLE_USER }
        - { path: ^/, roles: PUBLIC_ACCESS }